simulacro/Models/Company.cs
namespace simulacro.Models 
{
    public class Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Nit{ get; set; }
        public string Address{ get; set; }
        public string Description{ get; set; }
        public string Logo{ get; set; }
        public string Phone { get; set; }
        public string LegalRepresentative{ get; set; }
        public int SectorId { get; set; }

    }
}

simulacro/Models/ErrorViewModel.cs
namespace simulacro.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

simulacro/Models/Sector.cs
namespace simulacro.Models 
{
    public class Sector 
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description{ get; set; }
        public string Author{ get; set; }
    }
}

simulacro/Controllers/CompaniesController.cs
using Microsoft.AspNetCore.Mvc; 
using Microsoft.EntityFrameworkCore;
using simulacro.Data;
using simulacro.Models;

namespace simulacro.Controllers
{
    public class CompaniesController : Controller
    {
        public readonly DBContext _context;
        public CompaniesController(DBContext context)
        {
            _context = context;
        }
        //////////////// BUSCAR Y LISTAR  //////////
        public async Task<IActionResult> Index(string buscar)
        {
            var companies = from company in _context.Companies select company;
            if (!string.IsNullOrEmpty(buscar))
            {
                companies = companies.Where(c => c.Name.Contains(buscar) || c.Phone.Contains(buscar) || c.LegalRepresentative.Contains(buscar) || c.Nit.Contains(buscar) || c.Address.Contains(buscar));
            }
            return View(await companies.ToListAsync());
        }

        //////////////// CREATE //////////
        public IActionResult Create(){
            return View();
        }
        [HttpPost]

        public IActionResult Create(Company company){
            _context.Companies.Add(company);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        //////////////// ELIMINAR  //////////
        public async Task<IActionResult> Delete(int id){
            var company = await _context.Companies.FindAsync(id);
            _context.Companies.Remove(company);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        ////////////////  DETAILS  //////////
        public async Task<IActionResult> Details(int id){
            return View(await _context.Companies.FindAsync(id));
        }

        //////////////// EDITAR  //////////
        
        public async Task<IActionResult> Edit(int id){
            return View(await _context.Companies.FindAsync(id));
        }
        [HttpPost]
        public IActionResult Edit(Company company){
            _context.Companies.Update(company);
            _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

simulacro/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using simulacro.Models;

namespace simulacro.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

simulacro/Controllers/SectorsController.cs
using Microsoft.AspNetCore.Mvc; 
using Microsoft.EntityFrameworkCore;
using simulacro.Data;
using simulacro.Models;


namespace simulacro.Controllers
{
    public class Sectors(DBContext dbcontext) : Controller
    {
        //////////////// LISTAR Y BUSCAR  //////////
        public readonly DBContext _dbcontext = dbcontext;
        public async Task<IActionResult> Index(string buscar){
            var sectors = from sector in _dbcontext.Sectors select sector;
            if(!string.IsNullOrEmpty(buscar)){
                sectors = sectors.Where(s => s.Name.Contains(buscar) || s.Author.Contains(buscar));
            }
            return View(await sectors.ToListAsync());
        }
        //////////////// CREAR  //////////
        public IActionResult Create(){
            return View();
        }

        [HttpPost]
        public IActionResult Create(Sector sector){
            _dbcontext.Sectors.Add(sector);
            _dbcontext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        //////////////// ELIMINAR  //////////
        public async Task<IActionResult> Delete(int id){
            var sector = await _dbcontext.Sectors.FindAsync(id);
            _dbcontext.Sectors.Remove(sector);
            await _dbcontext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
         //////////////// DETALLES  //////////
        public async Task<IActionResult> Details(int id){
            return View(await _dbcontext.Sectors.FindAsync(id));
        }
        //////////////// EDITAR  //////////
        public async Task<IActionResult> Edit(int id){
            return View(await _dbcontext.Sectors.FindAsync(id));
        }
        [HttpPost]
        public IActionResult Edit(Sector sector){
            _dbcontext.Sectors.Update(sector);
            _dbcontext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

simulacro/Views/Companies/Create.cshtml
@model Company

<div class="row">
    <div class="col-md-4">
        <form aps-action="Create" method="post">
           
            <div class="mb-3">
                <label for="" class="form-label">Nombre</label>
                <input  class="form-control" asp-for="Name">
            </div>

            <div class="mb-3">
                <label for="" class="form-label">Nit</label>
                <input  class="form-control" asp-for="Nit">
            </div>
            <div class="mb-3">
                <label for="" class="form-label">direccion</label>
                <input  class="form-control" asp-for="Address">
            </div>
            <div class="mb-3">
                <label for="" class="form-label">dESCRIPCION</label>
                <input  class="form-control" asp-for="Description">
            </div>
            <div class="mb-3">
                <label for="" class="form-label">URL logo</label>
                <input  class="form-control" asp-for="Logo">
            </div>

            <div class="mb-3">
                <label for="" class="form-label">Numero</label>
                <input  class="form-control" asp-for="Phone">
            </div>  
            <div class="mb-3">
                <label for="" class="form-label">Representante legal</label>
                <input  class="form-control" asp-for="LegalRepresentative">
            </div>    

            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>
</div>

simulacro/Views/Companies/Delete.cshtml
<a asp-action="Index" asp-controller="Companies">volver</a>

simulacro/Views/Companies/Details.cshtml
<table class="table table-striped">
     <thead>
        <th># id</th>
        <th>Logo</th>
        <th>NIT</th>
        <th>Nombre</th>
        <th>Direccion</th>
        <th>Descripcion</th>
        <th>autor</th>
    </thead>
    </thead>
    <tbody>
       <tr>
                <td>@Model.Id</td>
                <td><img src="@Model.Logo" style="width: 100%;"> </td>
                <td>@Model.Nit</td>
                <td>@Model.Name</td>
                <td>@Model.Address</td>
                <td>@Model.Description</td>
                <td>@Model.LegalRepresentative</td>
       </tr>
    </tbody>
</table>

<a asp-controller="Sectors" asp-action="Index"> 
    <button class="btn btn-success" type="submit">volver</button>
</a>

simulacro/Views/Companies/Edit.cshtml
@model Company;

<div class="row">
    <div class="mb-3">

        <form asp-action="Edit" asp-controller="Companies">
            <div class="mb-3">
                <label for="" class="form-label">Nombre</label>
                <input  class="form-control" asp-for="@Model.Name">
            </div>

            <div class="mb-3">
                <label for="" class="form-label">URL logo</label>
                <input  class="form-control" asp-for="@Model.Logo">
            </div>
            <div>
                <label for="" class="form-label">NIT</label>
                <input  class="form-control" asp-for="@Model.Nit">
            </div>
            <div>
                <label for="" class="form-label">Direccion</label>
                <input  class="form-control" asp-for="@Model.Address">
            </div>
            <div>
                <label for="" class="form-label">Descripcion</label>
                <input  class="form-control" asp-for="@Model.Description">
            </div>
            <div>
                <label for="" class="form-label">Representante Legal</label>
                <input  class="form-control" asp-for="@Model.LegalRepresentative">
            </div>
            
            <button type="submit">EDITAR</button>
        </form>
    </div>

</div>

simulacro/Views/Companies/Index.cshtml
<form asp-controller="Companies" asp-action="Index">
  <p>
    buscar:<input type="text" name="buscar" class="form-text"/>
    <input type="submit" class="btn btn-sm btn-dark" placeholder="buscar"> 
  </p>

</form>

<div class="d-grid gap-2 col-6 mx-auto">
  <a class="btn btn-success" asp-action="Create" asp-controller="Companies">Crear Nuevo Sector</a>
</div>

<table class="table table-striped">
    <thead>
        <th># id</th>
        <th>Logo</th>
        <th>NIT</th>
        <th>Nombre</th>
        <th>Direccion</th>
        <th>Descripcion</th>
        <th>autor</th>
        <th>Acciones</th>
    </thead>
    <tbody>
       @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td><img src="@item.Logo" style="width: 100%;"> </td>
                <td>@item.Nit</td>
                <td>@item.Name</td>
                <td>@item.Address</td>
                <td>@item.Description</td>
                <td>@item.LegalRepresentative</td>
                <td> 
                    <a class="btn btn-info" asp-action="Edit" asp-controller="Companies" asp-route-id="@item.Id">Editar</a>
                    <a class="btn btn-warning" asp-action="Details" asp-controller="Companies" asp-route-id="@item.Id">Ver Detalles</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-controller="Companies" asp-route-id="@item.Id" >Eliminar</a>
                </td>
            </tr>
        } 
    </tbody>
</table>

simulacro/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

simulacro/Views/Sectors/Create.cshtml
@model Sector

<div class="row">
    <div class="col-md-4">
        <form aps-action="Create" method="post">
           
            <div class="mb-3">
                <label for="" class="form-label">Nombre</label>
                <input  class="form-control" asp-for="Name">
            </div>

            <div class="mb-3">
                <label for="" class="form-label">Descripcion</label>
                <input  class="form-control" asp-for="Description">
            </div>

            <div class="mb-3">
                <label for="" class="form-label">autor</label>
                <input  class="form-control" asp-for="Author">
            </div>

            
            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>
</div>

simulacro/Views/Sectors/Delete.cshtml
<a asp-action="Index" asp-controller="Companies">volver</a>

simulacro/Views/Sectors/Details.cshtml
<table class="table table-striped">
   <thead>
        <th># id</th>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>autor</th>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Id</td>
            <td>@Model.Name</td>
            <td>@Model.Description</td>
            <td>@Model.Author</td>
        </tr>
    </tbody>
</table>

<a asp-controller="Sectors" asp-action="Index"> 
    <button class="btn btn-success" type="submit">volver</button>
</a>

simulacro/Views/Sectors/Edit.cshtml
@model Sector;

<div class="row">
    <div class="mb-3">

        <form asp-action="Edit" asp-controller="Sectors">
            <div class="mb-3">
                <label for="" class="form-label">Nombre</label>
                <input  class="form-control" asp-for="@Model.Name">
            </div>

            <div class="mb-3">
                <label for="" class="form-label">Descripcion</label>
                <input  class="form-control" asp-for="@Model.Description">
            </div>
            <div>
                <label for="" class="form-label">Autor</label>
                <input  class="form-control" asp-for="@Model.Author">
            </div>
            <button type="submit">EDITAR</button>
        </form>
    </div>

</div>

simulacro/Views/Sectors/Index.cshtml
<form asp-controller="Sectors" asp-action="Index">
    <p>
        buscar:<input type="text" name="buscar" class="form-text"/>
        <input type="submit" value="buscar" class="btn btn-sm btn-dark"> 
    </p>
</form>

<div class="d-grid gap-2 col-6 mx-auto">
  <a class="btn btn-success" asp-action="Create" asp-controller="Sectors">Crear Nuevo Sector</a>
</div>


<table class="table table-striped">
    <thead>
        <th># id</th>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>autor</th>
        <th>Acciones</th>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Description</td>
                <td>@item.Author</td>
                <td> 
                    <a class="btn btn-info" asp-action="Edit" asp-controller="Sectors" asp-route-id="@item.Id">Editar</a>
                    <a class="btn btn-warning" asp-action="Details" asp-controller="Sectors" asp-route-id="@item.Id">Ver Detalles</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-controller="Sectors" asp-route-id="@item.Id">Eliminar</a>
                </td>
            </tr>
        } 
    </tbody>
</table>

simulacro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - simulacro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/simulacro.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">simulacro</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sectors" asp-action="Index">Sectors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="Index">Compañias</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - simulacro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>